apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: elasticsearch
spec:
  ports:
  - name: db
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    run: elasticsearch
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      run: elasticsearch
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: elasticsearch
    spec:
      nodeSelector:
        skywalking: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: skywalking
                operator: In
                values:
                - "true"
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "skywalking"
        effect: "NoSchedule"
      containers:
      - env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx8g"
        - name: indices.memory.index_buffer_size
          value: "50%"
        - name: thread_pool.write.queue_size 
          value: "10000"
        - name: thread_pool.bulk.queue_size
          value: "5000"
        - name: indices.queries.cache.size
          value: "40%"
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: tramsport
          protocol: TCP
status: {}
